var data = [
    {   name:"Reverend Insanity",
        pic:"Resources/ReverendInsanity/reverendInsanity.png" ,
        author:"Gu Zhu Ren Zhu",
        synopsis:"A story of a villain, Fang Yuan who was reborn 500 years into the past with the Spring Autumn Cicada he painstakingly refined. With his profound wisdom, battle and life experiences, he seeks to overcome his foes with skill and wit! Ruthless and amoral, he has no need to hold back as he pursues his ultimate goals. In a world of cruelty where one cultivates using Gu – [magical creatures of the world] – Fang Yuan must rise up above all with his own power.",
        slug:"reverend-insanity",
        rating:10,
        review:"A compelling read that strays from the standard xianxia/xuanhuan trope. Gu Zhen Ren narrates a story with a completely developed character in a word that has one of the best story building in modern day stories. Every volume ends with a bang and keeps the reader interested",
        protagonist:"Gu Yue Fang Yuan is a ruthless cold calculating human who chooses benefits and resources over everything else. Rules, allies, enemies, good, evil—these are all just concepts that are exploited for the sole goal of personal advancement. We witness him utilizing any means necessary like blackmailing, stealing, betrayal, alliances with former enemies for the sake of achieving his goal of an eternal life.",
        charactersAndWorld:"The supporting characters are rich and the world building is great. Every character other than the protagonist is dynamic with their own thoughts and personalities, a topic usually overlooked in standard xianxia/xuanhuan novels. The book never fails to surprise and every plot twist keeps you engaged. The world is split into 5 regions with each of them having their own cultures and traditions. The world is generally aligned into either the righteous path or the demonic path with the line demarcating them ever blurry.",
        addresses:"The novel addresses and talks about ideas such as destiny, power, individuality, death, rebellion against fate and perseverance. One of the most interesting aspects is that Fang Yuan as a character has no redemption arc or anything along those lines. Rather than talking about a character that keeps on developing, this novel takes an already developed character and tells the story from his perspective.",
        cons:"There are a few minor issues with the novel. Like any other standard web novel, the same concept is explained again and again and again to keep the reader interested. Also a few arcs like the northern plains arc could have been cut short drastically without affecting the storyline at all. The translations at some parts are iffy at the best",
        judgement:"Overall a fun read that could make the reader think and potentially change the way the reader looks at life. ",
        webnovel: true
    },
    {   name:"The Fifth Science",
        pic:"Resources/FifthScience/fifthScience.jpg" ,
        author:"exurb1a",
        synopsis:"The Galactic Human Empire was built atop four sciences: logic, physics, psychology, and sociology. Standing on those pillars, humans spent 100,000 years spreading out into the galaxy: warring, exploring, partying — the usual. Then there was the fifth science. And that killed the empire stone dead. The Fifth Science is a collection of 12 stories, beginning at the start of the Galactic Human Empire and following right through to its final days. We’ll see some untypical things along the way, meet some untypical folk: galactic lighthouses from the distant future, alien tombs from the distant past, murderers, emperors, archaeologists and drunks; mad mathematicians attempting to wake the universe itself up.",
        slug:"fifth-science",
        rating:9,
        review:"A collection of short stories that are loosely connected. An amazing read that deals with humanity, existentialism, philosophy and morality in a quirky humorous way. The story is based on how the fifth science led to the fall of the galactic human empire that spanned across hundreds of thousands of units of space and time. Each of the short stories deals with different aspects of human existence and provokes thoughts while still being simple and straightforward.",
        addresses:"Deals with complex topics such as being human, making sentient beings conscious, human existence in simple stories that are thought provoking and easy to understand at the same time. Ideas such as the entire galaxy being a sentient thought entity with each of the star being a processing unit [which kinda makes sense if you’ve read about artificial neural networks] are discussed in the same quirky energetic manner like the content in exurb1a’s youtube channel",
        cons:"Some stories are breathtaking and insanely thought provoking. But some of them are just plain boring and bring down the standards of the rest of the book. There is also the issue of generalisation and trying to explain grand things that can’t be explained using current technology by trying to force them into current standards. [disclaimer - The author might be a sex offender, but I believe in the separation of the book and it’s author and the review won’t change irrespective of the ruling]",
        judgement:"A good read for people of any age. Extremely thought provoking and not recommended unless the reader is willing to spend time on making peace with their existential crisis and sense of self.",
        webnovel: false
    },
    {   name:"Beyond Good and Evil",
        pic:"Resources/BeyondGoodAndEvil/beyondGoodAndEvil.jpg" ,
        author:"Friedrich Nietzsche",
        synopsis:"Beyond Good and Evil is a comprehensive overview of Nietzsche's mature philosophy. The book consists of 296 aphorisms, ranging in length from a few sentences to a few pages. These aphorisms are grouped thematically into nine different chapters and are bookended by a preface and a poem.",
        slug:"beyond-good-and-evil",
        rating:8,
        review:"Beyond good and evil is just an angry old man’s ramblings against society. But this rambling in itself is interesting and fun to read. The book feels like an anthology of similarly themed rants of a sad man who’s had too much time to think about life, morals and society. The poem in the end is an amazing take on friendship and individuality.",
        addresses:"Deals with topics such as morals, how morals affect society, how ‘herd’ mentality is prevalent in society, how individuality is more important than social norms. The ‘noble’ part of his work that says how everyone is on a quest to make their own sense of this chaotic world resonates with my own sense of understanding of how this world works. His criticism against religion is an interesting take on how people lose their individuality.",
        cons:"Nietzsche was a misogynist. Though progressiveish for his time, the time held him back. There was also this added layer of sophistication that was not necessary and ruined the meaning of the book. ",
        judgement:"Good place to get started into reading books on philosophy. Would recommend using a helper book if it feels too complicated for your first read.",
        webnovel: false
    },
    {   name:"Lord of the Mysteries",
        pic:"Resources/LordOfTheMysteries/lordOfTheMysteries.png" ,
        author:"Cuttlefish That Loves Diving",
        synopsis:"Set with the historical backdrop of an alternate 19th century Victorian London, the protagonist Zhou Mingrui finds himself having transmigrated into the body of Klein Moretti, a recent history graduate in Tingen City. Faced with perplexing mysteries and strange, supernatural events, he quickly realizes things are not what they appear. Filled with cannons, battleships, steam engines, and factories, as well as divination, potions, tarot cards, sealed artifacts, and superhumans known as Beyonders, Klein finds himself the unwitting leader of a secret organization, known only to his followers as 'The Fool'. Join Klein as he becomes a Beyonder, advancing in power and uncovering the mysteries of the world.",
        slug:"lord-of-the-mysteries",
        rating:10,
        review:"Lord of the mysteries is an excellent book that deals with the question what does it mean to be a human. Zhou Mingrui gets transmigrated into the body of Klein Moretti, in a world that recently entered the industrial age. In the presence of beings of supernatural entities, this is the story of Klein’s apotheosis from a human to a God told in the perspective of Klein himself. Book written in a cthulhu mythos format and heavily references to norse mythology. The book also has heavy references to occult sciences.",
        protagonist:"Klein Moretti is a calm, cautious and a good natured human. Fundamentally being a follower of justice, He chooses to side with justice even at personal cost. We see how Klein changes from a slightly indecisive cautious newbie to someone more ruthless, confident, and mysterious compared to his former mentality. Even so, he preserves the core of his personality as one who is cautious, yet will uphold justice where necessary and not involve or target the innocent.",
        charactersAndWorld:"LotM is a book with great supporting characters and a rich world that doesn’t cease to surprise. All the characters have their own personalities, their traits, their quirks and their values that makes them feel real and multi-dimensional. The characters are varied and show live in the perspective of all the different people in 18th centuryish England ",
        addresses:"Deals with topics like what it means to be human, till what point can a being with godlike powers can be considered human, the difference in the lifestyles of people belonging to different classes in industrial England, fate and even how everything bestowed comes with a price. Thought provoking and and at the same time entertaining as a story",
        cons:"The ending is extremely hurried and a lot of loose ends are left. This is intentional as the author plans on writing a sequel, but at the moment, it ends without a proper closure giving the invested readers who have read around 1400 chapters a sense of emptiness.",
        judgement:"Amazing book that’s a must read for all mystery and occult fans. Extremely entertaining and captures the reader’s heart. AMazinglyHilarious and quirky while still keeping a sense of seriousness.",
        webnovel: true

    },
    {   name:"Xian Ni {Renegade Immortal}",
        pic:"Resources/RenegadeImmortal/renegadeImmortal.jpg" ,
        author:"Er Gen",
        synopsis:"Wang Lin is a very smart boy with loving parents. Although he and his parents are shunned by the rest of their relatives, his parents have always held high hopes that he will one day achieve greatness. One day, Wang Lin suddenly gained the chance to walk the path of an immortal but found that he only had mediocre talent at best. Watch Wang Lin as he breaks through his lack of talent and walks the path towards becoming a real immortal! ",
        slug:"xian-ni",
        rating:8,
        review:"Xian Ni is a good read that doesn't follow the standard xianxia/xianhuan tropes. An intelligent read that tells the story of Wang Lin, a young filial boy who carries the hope of his family and the way the world around him that shapes him. Only negative point in the book is the HORRIBLE romance. The book would have been waaaaay better off without the romance part in it.",
        protagonist:"Wang Lin is a multidimensional character moulded by the uiverse he resides in. We witness as he changes from a naive young boy shouldering the hopes of his family to the point when he becomes a cold blooded, ruthless murderer who tries to achieve a simple goal of living a life where he isn't bounded by anyone. Even though he commits wanton acts of murder, he still retains his morals not in the sense of being a hypocrite, but in the sense of being a human.",
        charactersAndWorld:"The world in Xian Ni is a dark and depressing one that has some coulourful parts to it. The system of power in the book is well defined and the parts that contain Wang Lin's dao comprehension as well as the mortal arcs are really good. Some of the antagonists and supporting characters are momorable and have a really strong part in the narrative process. The very start of the book lacks the sense of severity of actions that's found in the rest of the book. Some stuff do end up being inconsistent in the long run as the novel has around 2000 chapters.",
        addresses:"Xian Ni tells how humans are shaped by their circumstances. In a dark, gritty world where personal power is valued that most, the characters that come out are going to be dark and gritty themselves. The books also talks about life, death and how the very knowledge of life and death of loved ones can change a person to the point that that they would become unrecognisable.",
        cons:"Horrible romance. Absolutely horrible to the extent that the romance brings down the quality of the entire book. A considerable number of plotholes that could possibly break the story. Some exaggerated details like beings of like millions of kilometers in size sorta destroy the ability that makes people imagine",
        judgement:"A good read for a newbie in xianxia/xuanhuan. Keeps reader engaged throughout the story. Well written characters keeps you interested. Same issue of repeating the same stuff over and over again still exists",
        webnovel: true

    },
    {   name:"World Of Cultivation",
        pic:"Resources/WorldOfCultivation/worldOfCultivation.jpg" ,
        author:"Fang Xiang",
        synopsis:"Some are born great, some achieve greatness and some have greatness thrust upon them. Zuo Mo is a zombie faced low level cultivator in a minor sect of a little world. Ever since he was picked up by the sect leader two years ago, he has no memories of his earlier life except a recurring nightmare. Navigating the rigid class structure and intricacies of the cultivation world, as one of the lowest possible of the lowest class, Zuo Mo’s dream is to earn money, and lots of it, through being a spiritual plant farmer. A chance occurrence reveals that someone powerful had changed Zuo’s features and erased his mind. The money grubbing zombie decides to set out on a journey of cultivation to find out answers. Fate colludes with chance, the drums of war are beating, the ghost of his past is coming…",
        slug:"world-of-cultivation",
        rating:7,
        review:"World of cultivation is a fresh xianxia that shows how good a web novel could be if the author chooses to actually plot out the story instead of fleshing it out. The novel doesn’t suffer from the standard cliched hero and 1D characters. It has some creative ideas along with memorable recurring characters. We see the protagonist Zuo Mo who started off farming, preferring a life of earning money, enter the world of martial arts and cultivation and creating his own force that could decide the fate of the world.",
        protagonist:"Shameless. Thick-skinned. Money-minded. Shrewd. The protagonist is realistic and lifelike. When compared to Wei Sheng, who seems more of a standard xianxia protagonist with his “unyielding will” and sword talent, Zuo Mo spends his time thinking of making money. His existence is like a breath of fresh air when compared to the standard xianxia novel.",
        charactersAndWorld:"As a novel with “World of Cultivation” in its title, it delivers. Great world building with memorable characters that don’t feel bland. No one or no group exactly feels like an antagonistic entity. Each character is driven by their own motivation. But the author fails to keep up with the expanding world building in the end and ends up losing the main factor that kept the book interesting and different from its peers.",
        addresses:" Main ideology in the book is conflict and wars. It tells a tale of the pitiful existence of an individual when faced against the tides of war. It’s also a tale of friendship, humour and faction building. The story has a very “human” feeling in it.",
        cons:"A very hurried ending. Quite a few plot holes in the magic system that’s being used. Poor romance and missed chances. Feels as if the author who finished the second half of the book was a different one. A lot of plot holes that could break the experience of the book. Some characters are introduced and then forgotten. Quite a number of characters, including the sect leaders of the MC are just killed off in the background, making the plot feel like it’s barely held together.",
        judgement:" Standard example of a book with a good theory and idea coupled with bad execution.",
        webnovel: true
    }
    
]

module.exports = data
